"""add test data

Revision ID: 5c680a467d9f
Revises: 66a49d3eb3d5
Create Date: 2023-11-27 17:21:16.894532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c680a467d9f'
down_revision = '66a49d3eb3d5'
branch_labels = None
depends_on = "66a49d3eb3d5"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    categories_table = sa.Table(
        'categories',
        sa.MetaData(),
        autoload_with=op.get_bind().engine
    )
    op.bulk_insert(
        categories_table,
        [
            {'category': 'Antiques'},
            {'category': 'Art'},
            {'category': 'Baby'},
            {'category': 'Books'},
            {'category': 'Business & Industrial'},
            {'category': 'Cameras & Photo'},
            {'category': 'Cell Phones & Accessories'},
            {'category': 'Clothing, Shoes & Accessories'},
            {'category': 'Coins & Paper Money'},
            {'category': 'Collectibles'},
            {'category': 'Computers/Tablets & Networking'},
            {'category': 'Consumer Electronics'},
            {'category': 'Crafts'},
            {'category': 'Dolls & Bears'},
            {'category': 'DVDs & Movies'},
            {'category': 'Entertainment Memorabilia'},
            {'category': 'Everything Else'},
            {'category': 'Gift Cards & Coupons'},
            {'category': 'Health & Beauty'},
            {'category': 'Home & Garden'},
            {'category': 'Jewelry & Watches'},
            {'category': 'Music'},
            {'category': 'Musical Instruments & Gear'},
            {'category': 'Pet Supplies'},
            {'category': 'Pottery & Glass'},
            {'category': 'Real Estate'},
            {'category': 'Specialty Services'},
            {'category': 'Sporting Goods'},
            {'category': 'Sports Mem, Cards & Fan Shop'},
            {'category': 'Stamps'},
            {'category': 'Tickets & Experiences'},
            {'category': 'Toys & Hobbies'},
            {'category': 'Travel'},
            {'category': 'Video Games & Consoles'},
            {'category': 'Other'},
        ]
    )

    items_table = sa.Table(
        'items',
        sa.MetaData(),
        autoload_with=op.get_bind().engine
    )

    op.bulk_insert(
        items_table,
        [
            {'title': 'Abstract Canvas Painting', 'shipping_cost': 15.00, 'category_id': 2, 'initial_bid_price': 50.00, 'seller_id': 1},
            {'title': 'Sculpture: Marble Statue', 'shipping_cost': 20.00, 'category_id': 2, 'initial_bid_price': 200.00, 'seller_id': 3},
            {'title': 'Harry Potter Book Set', 'shipping_cost': 12.00, 'category_id': 4, 'initial_bid_price': 30.00, 'seller_id': 3},
            {'title': 'Vintage Poetry Collection', 'shipping_cost': 8.00, 'category_id': 4, 'initial_bid_price': 15.00, 'seller_id': 2},
            {'title': 'Smartphone: Latest Model', 'shipping_cost': 10.00, 'category_id': 11, 'initial_bid_price': 500.00, 'seller_id': 1},
            {'title': 'Laptop: High Performance', 'shipping_cost': 20.00, 'category_id': 11, 'initial_bid_price': 800.00, 'seller_id': 4},
            {'title': 'Designer Leather Jacket', 'shipping_cost': 15.00, 'category_id': 8, 'initial_bid_price': 120.00, 'seller_id': 2},
            {'title': 'Running Shoes: Limited Edition', 'shipping_cost': 10.00, 'category_id': 8, 'initial_bid_price': 80.00, 'seller_id': 3},
            {'title': 'Vintage Comic Books Set', 'shipping_cost': 12.00, 'category_id': 10, 'initial_bid_price': 50.00, 'seller_id': 4},
            {'title': 'Rare Coin Collection', 'shipping_cost': 18.00, 'category_id': 10, 'initial_bid_price': 150.00, 'seller_id': 1},
            {'title': 'Garden Furniture Set', 'shipping_cost': 25.00, 'category_id': 10, 'initial_bid_price': 200.00, 'seller_id': 5},
            {'title': 'Kitchen Appliances Bundle', 'shipping_cost': 15.00, 'category_id': 10, 'initial_bid_price': 120.00, 'seller_id': 2},
            {'title': 'LEGO Star Wars Millennium Falcon', 'shipping_cost': 10.00, 'category_id': 9, 'initial_bid_price': 100.00, 'seller_id': 3},
            {'title': 'Board Game Collection', 'shipping_cost': 8.00, 'category_id': 9, 'initial_bid_price': 30.00, 'seller_id': 4},
        ]
    )

    watchlists_table = sa.Table(
        'watchlists',
        sa.MetaData(),
        autoload_with=op.get_bind().engine
    )

    op.bulk_insert(
        watchlists_table,
        [
            {'user_id': 1, 'category_id': 2, 'max_price': 100.00},
            {'user_id': 1, 'category_id': 4, 'max_price': 50.00},
            {'user_id': 1, 'category_id': 11, 'max_price': 500.00},
            {'user_id': 1, 'category_id': 8, 'max_price': 200.00},
            {'user_id': 1, 'category_id': 10, 'max_price': 200.00},
            {'user_id': 1, 'category_id': 9, 'max_price': 100.00},
            {'user_id': 2, 'category_id': 2, 'max_price': 200.00},
            {'user_id': 2, 'category_id': 4, 'max_price': 100.00},
            {'user_id': 2, 'category_id': 11, 'max_price': 100.00},
            {'user_id': 2, 'category_id': 8, 'max_price': 500.00},
            {'user_id': 2, 'category_id': 10, 'max_price': 50.00},
            {'user_id': 2, 'category_id': 9, 'max_price': 200.00},
            {'user_id': 3, 'category_id': 2, 'max_price': 100.00},
            {'user_id': 3, 'category_id': 4, 'max_price': 500.00},
            {'user_id': 3, 'category_id': 11, 'max_price': 200.00},
            {'user_id': 3, 'category_id': 8, 'max_price': 100.00},
            {'user_id': 3, 'category_id': 10, 'max_price': 100.00},
            {'user_id': 3, 'category_id': 9, 'max_price': 50.00},
            {'user_id': 4, 'category_id': 2, 'max_price': 500.00},
            {'user_id': 4, 'category_id': 4, 'max_price': 100.00},
            {'user_id': 4, 'category_id': 11, 'max_price': 50.00},
            {'user_id': 4, 'category_id': 8, 'max_price': 200.00},
            {'user_id': 4, 'category_id': 10, 'max_price': 200.00},
            {'user_id': 4, 'category_id': 9, 'max_price': 100.00},
            {'user_id': 5, 'category_id': 2, 'max_price': 1000.00},
            {'user_id': 5, 'category_id': 4, 'max_price': 20.00},
            {'user_id': 5, 'category_id': 11, 'max_price': 100.00},
            {'user_id': 5, 'category_id': 8, 'max_price': 500.00},
            {'user_id': 5, 'category_id': 10, 'max_price': 500.00},
            {'user_id': 5, 'category_id': 9, 'max_price': 20.00},
        ]
    )

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
