version: "3"
services:
  vite-client:
    build:
      context: ./vite-client
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUCTION_URL=http://auction-service:3001/
      - USER_URL=http://user-service:3002/
    container_name: vite-client
    depends_on:
      auction-service:
        condition: service_started
      user-service:
        condition: service_started
    volumes:
      - ./vite-client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    stop_signal: SIGKILL

  db-service:
    build: ./db-service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=3004
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-service:/usr/src/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  db-gateway-service:
    build: ./db-gateway-service
    environment:
      - PORT=3003
      - PGHOST=db-service
      - PGPORT=3004
      - PGDATABASE=auctiondb
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - db-service

  auction-service:
    build: ./auction-service
    environment:
      - PORT=3001
    volumes:
      - ./auction-service:/usr/src/app
      - auction_node_modules:/usr/src/app/node_modules
    stop_signal: SIGKILL

  user-service:
    build: ./user-service
    environment:
      - PORT=3002
    volumes:
      - ./user-service:/usr/src/app
    stop_signal: SIGKILL

volumes:
  client_node_modules:
  auction_node_modules:
  db_data:
